// styles.js
import {StyleSheet} from 'react-native';
import Colors from './color';
// const globalStyles = colors =>
//   StyleSheet.create({
const globalStyles = StyleSheet.create({
  SafeAreaView: {
    flex: 1,
  },
  FX_1_BG_LiteGray: {
    flex: 1,
    // backgroundColor: Colors.lite_gray
  },
  FX_1_BG_White: {
    flex: 1,
    // backgroundColor: Colors.white
  },
  MainView: {
    flex: 1,
    marginHorizontal: 12,
  },
  listEucation: {
    marginHorizontal: 12,
    //backgroundColor: Colors.background_Profile_Tag,
    borderRadius: 20,
    padding: 10,
    marginVertical: 5,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  flexRow: {flexDirection: 'row'},
  dateSection: {
    paddingTop: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  saveButton: {
    borderRadius: 4,
    paddingVertical: 15,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
  },
  saveButtonText: {
    fontSize: 15,
    fontWeight: '700',
  },
  moreText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#000',
  },
  moreContainer: {
    width: 94,
    height: 94,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#d3d3d3',
    borderRadius: 8,
  },
  smallImagesColumn: {
    flexDirection: 'column',
    justifyContent: 'flex-start',
  },
  contantlistImage: {
    width: 61,
    height: 61,
    borderRadius: 40,
    marginRight: 5,
    borderWidth: 3,
    borderColor: 'yellow',
  },
  contantlistMainView: {
    // backgroundColor: Colors.white,
    flexDirection: 'row',
    padding: 20,
    marginHorizontal: 10,
    borderBottomWidth: 0.5,
    alignItems: 'center',
  },
  PendingIcons: {
    borderWidth: 1,
    padding: 10,
    borderRadius: 20,
    marginRight: 10,
  },
  skillValueMainView: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  skllSecondView: {
    marginVertical: 5,
    marginRight: 5,
    padding: 10,
    //  backgroundColor: Colors.background_Profile_Tag,
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
  },
  skillText: {fontSize: 14},
  ProfileDetailViewText: {
    fontSize: 18,
    fontWeight: '600',
  },
  PDMainView: {
    marginHorizontal: 14,
    paddingVertical: 10,
    marginTop: 10,
    borderBottomWidth: 1,
    // borderColor: Colors.borderColor,
  },
  ArticlesListView: {
    // backgroundColor: Colors.white,
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: 12,
    paddingLeft: 10,
    marginTop: 10,
  },
  JoinArticle: {
    flex: 0.4,
    padding: 10,
    justifyContent: 'center',
    //backgroundColor: Colors.main_primary,
    margin: 10,
    borderRadius: 10,
    flexDirection: 'row',
  },
  JoinText: {fontWeight: '600'},
  ViewUserDetils: {
    // backgroundColor: Colors.white,
    marginHorizontal: 12,
    marginTop: 10,
    padding: 10,
    flexDirection: 'row',
    alignItems: 'center',
    borderTopWidth: 1,
    borderBottomWidth: 1,
    marginVertical: 15,
    //borderColor: Colors.borderColor,
  },
  ViewUserDetilsIMG: {
    height: 80,
    width: 80,
    borderRadius: 10,
    borderRadius: 40,
    borderWidth: 2,
    borderColor: 'yellow',
  },
  MoreArticleView: {
    //backgroundColor: Colors.white,
    marginHorizontal: 12,
    marginTop: 10,
    padding: 10,
  },
  MoreArticleText: {fontSize: 20, fontWeight: '700'},
  shareButtonView: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  input: {
    flex: 1,
    paddingVertical: 8,
    paddingRight: 30,
    paddingHorizontal: 10,
    fontSize: 14,
    color: '#000',
  },
  ViewINter1: {
    paddingVertical: 10,
    paddingLeft: 10,
    marginHorizontal: 8,
  },
  ViewINter: {
    paddingVertical: 10,
    alignItems: 'center',
    //backgroundColor: 'white',
  },
  headlineText: {fontSize: 16, fontWeight: '600'},
  OwnView: {
    alignItems: 'center',
    paddingVertical: 20,
    backgroundColor: 'white',
  },
  OwnViewIcon: {
    backgroundColor: Colors.secondGreen,
    padding: 20,
    borderRadius: 30,
    marginRight: 5,
  },
  OwnViewText1: {fontSize: 15, flexShrink: 1},
  OwnViewText2: {
    color: Colors.secondGreen,
    fontWeight: '700',
    fontSize: 15,
  },
  HeadText: {
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 10,
  },
  headView: {
    paddingVertical: 20,
    borderBottomWidth: 1,
    //borderColor: Colors.borderColor,
  },
  SearchInputIntership: {
    marginTop: 30,
    paddingTop: 12,
    paddingHorizontal: 10,
    backgroundColor: 'white',
    fontSize: 14,
    borderWidth: 0.5,
    borderColor: 'gray',
    borderRadius: 5,
    height: 40,
  },
  HeadeViewIcon: {
    flexDirection: 'row',
    marginVertical: 10,
  },
  HeadeViewIcon2: {
    flex: 1,
    //backgroundColor: Colors.white,
    alignItems: 'center',
    borderRightWidth: 1,
    //borderColor: Colors.borderColor,
    padding: 5,
    paddingVertical: 10,
  },
  HeadeViewTouch: {
    backgroundColor: Colors.secondGreen,
    padding: 10,
    borderRadius: 10,
    alignItems: 'center',
  },
  JobfiledSection: {paddingTop: 10},
  Myintern: {
    padding: 15,
    borderBottomWidth: 1,
    //borderColor: Colors.borderColor,
  },
  FlatListView: {
    // backgroundColor: Colors.secondGreen,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
    marginRight: 10,
  },
  FlatList2: {
    flexDirection: 'row',
    marginVertical: 5,
    alignItems: 'center',
  },
  FlatListText: {fontSize: 15, fontWeight: '700'},
  ImageView: {
    width: 40,
    height: 40,
    marginRight: 5,
    borderWidth: 2,
    borderColor: 'yellow',
    borderRadius: 20,
  },
  FlatListIconView: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 0.2,
  },
  SearchInternText: {fontWeight: '700'},
  SeekerText: {
    // color: Colors.secondGreen,
    fontSize: 16,
    fontWeight: '600',
  },
  jobLevelView: {
    borderWidth: 1,
    // borderColor: Colors.borderColor,
    margin: 20,
  },
  jobLevelImg: {width: 'auto', height: 150},
  jobLevelView2: {flexDirection: 'row', justifyContent: 'space-between'},
  jobLevelText: {fontSize: 16, fontWeight: '600', padding: 5},
  jobLevelText1: {
    fontSize: 15,
    fontWeight: '800',
    padding: 5,
    // color: Colors.main_primary,
  },
  JobLevText: {color: 'white', fontSize: 13, fontWeight: '800'},

  JobfiledSectionText: {fontSize: 13, paddingBottom: 10},
  textInput: {
    paddingTop: 12,
    paddingHorizontal: 10,
    fontSize: 14,
    borderWidth: 0.5,
    // borderColor: 'gray',
    borderRadius: 5,
    height: 40,
    textAlignVertical: 'top',
    // color: 'black',
  },

  seclectIndiaView: {
    marginTop: 5,
    borderWidth: 0.5,
    borderRadius: 5,
    paddingVertical: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 10,
  },
  dropdownList: {
    marginTop: 5,
    borderWidth: 1,
    borderRadius: 5,
    // backgroundColor: '#fff',
    margin: 10,
    padding: 10,
  },
  dropdownItem: {
    padding: 10,
    borderBottomWidth: 1,
    // borderBottomColor: '#ddd',
  },
  containerSkill: {flex: 1, padding: 10},
  inputContainerSkill: {flexDirection: 'row'},
  skillTag: {
    // backgroundColor: Colors.secondGreen,
    padding: 8,
    margin: 5,
    borderRadius: 20,
  },

  skillText: {fontWeight: 'bold'},
  addButton: {
    // backgroundColor: Colors.secondGreen,
    padding: 12,
    marginLeft: 10,
    borderRadius: 8,
  },

  addText: {fontWeight: 'bold'},

  inputSkill: {
    flex: 1,
    borderWidth: 1,
    padding: 10,
    borderRadius: 8,
    borderColor: '#ccc',
    color: 'black',
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  modalContent: {
    width: '80%',
    //  backgroundColor: 'white',
    borderRadius: 10,
    padding: 20,
    alignItems: 'center',
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.25,
    shadowRadius: 4,
  },
  inputField: {
    width: '100%',
    borderWidth: 1,
    //borderColor: '#ccc',
    borderRadius: 5,
    padding: 10,
    marginVertical: 10,
    fontSize: 16,
  },
  centeredView: {
    flex: 1,
    justifyContent: 'flex-end',
  },

  modalView: {
    flex: 0.46,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    padding: 20,
    paddingVertical: 10,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  textInputComment: {
    flex: 1,
    paddingLeft: 40,
    paddingVertical: 20,
    fontSize: 14,
    // borderWidth: 0.5,
    // borderColor: 'gray',
    // borderRadius: 5,
    position: 'relative',
  },
  ViewCommentImg: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 10,
    position: 'relative',
    borderWidth: 0.5,
    borderRadius: 5,
  },
  ImgComment: {
    width: 30,
    height: 30,
    position: 'absolute',
    marginLeft: 5,
    borderRadius: 30,
  },
  commentTitle: {
    fontSize: 15,
    padding: 15,
    fontWeight: '700',
  },

  modalText: {
    marginBottom: 15,
    fontSize: 16,
    fontWeight: '700',
  },

  inputShare: {
    flex: 1,
    paddingVertical: 8,
    paddingRight: 30,
    paddingHorizontal: 10,
    fontSize: 14,
    color: '#000',
  },

  dropdownListShare: {
    marginTop: 5,
    borderWidth: 1,
    borderRadius: 4,
  },
  dropdownItemShare: {
    padding: 10,
    borderBottomWidth: 1,
  },
  // Flex
  FD_Row_AT_C: {
    flexDirection: 'row',
    alignItems: 'center',
  },

  AI: {alignItems: 'center'},
  // Margin

  MT_20: {marginTop: 20},
  MV_10: {marginVertical: 10},
  MH_30: {marginHorizontal: 30},
  MH_10_PV_30: {marginHorizontal: 10, paddingVertical: 30},
  MT_20_PH_10: {
    marginTop: 20,
    paddingHorizontal: 10,
  },

  // Padding
  P_10: {padding: 10},
  PT: {paddingTop: 10},
  PR_10: {paddingRight: 10},
  PV_10: {paddingVertical: 10},
  PV_AI: {paddingVertical: 10, alignItems: 'center'},

  //FontSize Only
  FS_15: {fontSize: 15},

  // Font Size with Wight
  FW_600: {fontWeight: '600'},
  FW_B: {fontWeight: 'bold'},
  FS_14_FW_B: {fontSize: 14, fontWeight: 'bold'},
  FS_16_FW_B: {fontSize: 16, fontWeight: 'bold'},
  FS_20_FW_B: {fontSize: 20, fontWeight: 'bold'},
  FS_18_CW: {fontSize: 18, color: Colors.white},
  FS_14_CW: {fontSize: 14, color: Colors.white},
  FS_20_FW_500: {fontSize: 20, fontWeight: '500'},
  FS_19_FW_500: {fontSize: 19, fontWeight: '500'},
  FS_18_FW_600: {fontSize: 18, fontWeight: '600'},
  FS_17_C_m_p: {fontSize: 17},
  FS_16_FW_400: {fontSize: 16, fontWeight: '600'},
  FS_15_CB_FW_600: {fontSize: 15, fontWeight: '600'},
  AS_End_PV_5: {alignSelf: 'flex-end', paddingVertical: 5},
  FD_Row_JC_SB: {flexDirection: 'row', justifyContent: 'space-between'},
  FD_Row_PV_5: {flexDirection: 'row', paddingVertical: 5},
  selectImgArticle: {
    marginTop: 20,
    borderWidth: 1,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 30,
  },
  firstImage: {
    width: 225,
    height: 225,
    marginRight: 10, // Spacing between big and small images
    borderRadius: 8,
  },
  containerArticle: {
    justifyContent: 'center',
    alignItems: 'center',
    padding: 10,
  },

  rowArticle: {
    flexDirection: 'row',
    alignItems: 'flex-start', // Align items at the top
  },
  InputTitle: {
    paddingHorizontal: 20,
    paddingVertical: 20,
    fontSize: 14,
    borderWidth: 0.5,
    // borderColor: 'gray',
    borderRadius: 5,
    position: 'relative',
    textAlignVertical: 'top',
    // color: 'black',
  },
  IconViewArticles: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 20,
  },
  TextArticles: {fontSize: 14, flexShrink: 1},
  GroupsListView: {
    height: 400,
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 20,
    marginVertical: 10,
    borderRadius: 10,
  },
  SecMainView: {
    backgroundColor: Colors.lite_gray,
    padding: 15,
    borderRadius: 80,
  },
  IConView: {
    padding: 25,
    borderRadius: 80,
  },
  TextGroupList: {fontSize: 17, fontWeight: '700', marginTop: 10},
  TextGroupList2: {fontSize: 15, marginVertical: 10},
  GroupModeratorImg: {
    width: 50,
    height: 50,
    borderRadius: 30,
    backgroundColor: Colors.lite_gray,
  },
  label: {
    fontSize: 16,
    paddingRight: 10,
    color: '#888',
  },
  GroupsChatView: {
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
  },
  SerachInput: {
    flex: 1,
    borderWidth: 1,
    borderRadius: 5,
    padding: 10,
  },
  SerachBtn: {
    // backgroundColor: Colors.main_primary,
    padding: 10,
    marginLeft: 5,
    borderRadius: 5,
    justifyContent: 'center',
  },
  ActionView: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: '90%',
    paddingVertical: 10,
  },
  ValueText: {
    // color: Colors.main_primary,
    fontSize: 16,
    fontWeight: 'bold',
  },
  optionBox: {
    flex: 1,
    padding: 10,
    margin: 5,
    alignItems: 'center',
    justifyContent: 'center',
    // backgroundColor: '#fff', // Default background
    // borderWidth: 1,
    // borderColor: Colors.borderColor,
  },
  optionText: {
    fontSize: 17,
    fontWeight: '700',
  },
  shareModal: {
    // backgroundColor: Colors.main_primary,
    padding: 10,
    borderRadius: 4,
    marginTop: 10,
    alignItems: 'center',
  },
  shareText: {fontWeight: 'bold'},
  shareModalMain: {
    flex: 1,
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  shareModalMain2: {
    padding: 20,
    borderRadius: 10,
    marginHorizontal: 20,
    marginTop: 20,
    height: '60%',
    // flex: 0.6,
  },
  shareText1: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 10,
  },
  shareInput: {
    borderWidth: 1,
    // borderColor: '#ddd',
    borderRadius: 5,
    padding: 10,
    marginBottom: 10,
    // color: 'black',
  },
  inputContainerChat: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    // paddingVertical: 10,
    borderTopWidth: 1,
  },
  ContalitTag: {
    flexDirection: 'row',
    padding: 10,
    borderWidth: 1,
    // borderColor: Colors.borderColor,
    marginVertical: 2,
    borderRadius: 5,
  },
  TagImg: {
    width: 61,
    height: 61,
    borderRadius: 40,
    marginRight: 5,
    borderWidth: 3,
    borderColor: 'yellow',
    backgroundColor: Colors.lite_gray,
  },
  PostTextViewINPut: {
    marginTop: 10,
    paddingVertical: 8,
    paddingHorizontal: 10,
    fontSize: 14,
    borderWidth: 0.5,
    borderRadius: 5,
    height: 70,
  },
  ImgUserProfile: {
    width: 41,
    height: 41,
    borderRadius: 20,
    marginRight: 5,
    borderWidth: 2,
    borderColor: 'yellow',
  },
  SelectTagViewMain: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#e0e0e0',
    padding: 8,
    borderRadius: 20,
    margin: 5,
  },
  SelectTagView: {
    width: 20,
    height: 20,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sectionView: {
    marginHorizontal: 12,
    borderBottomWidth: 0.5,
    padding: 10,
    paddingVertical: 15,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    margin: 5,
    borderRadius: 20,
  },
  sectionText: {marginRight: 20, fontSize: 16, fontWeight: '500'},
  PostImg: {
    width: 41,
    height: 41,
    borderRadius: 20,
    marginRight: 5,
    borderWidth: 2,
    borderColor: 'yellow',
  },
  SendBtn: {
    borderWidth: 0.5,
    width: 150,
    marginTop: 10,
    padding: 3,
    borderRadius: 20,
  },
  LikeListView: {
    margin: 10,
    borderBottomWidth: 1,
    borderColor: Colors.borderColor,
    paddingVertical: 20,
  },
  LikeView: {
    margin: 10,
    flexDirection: 'row',
    alignItems: 'center',
    paddingBottom: 10,
    borderBottomWidth: 1,
    // borderColor: Colors.borderColor,
  },
  LikeImg: {
    width: 40,
    height: 40,
    backgroundColor: 'red',
    borderRadius: 25,
  },
  LikeTitle: {
    // color: 'black',
    fontSize: 17,
    paddingBottom: 5,
    fontWeight: '600',
  },
  LikeTitle2: {fontSize: 17},
  SaveBtnView: {
    marginTop: 30,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  SaveBtn: {
    flex: 1,
    padding: 10,
    borderRadius: 5,
  },
  SaveBtnText: {
    fontSize: 18,
    fontWeight: '600',
    textAlign: 'center',
  },
  HLChagePW: {fontSize: 18, fontWeight: '600', padding: 10},
});

export default globalStyles;
